name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-12
    name: Build plugins
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@latest
    - name: FreeBSD VM
      id: build
      uses: vmactions/freebsd-vm@latest
      with:
        release: 14.1
        usesh: true
        sync: sshfs
        prepare: |
          pkg install -y git
          pkg install -y python
          pkg install -y php82
          pkg install -y rsync
        envs: 'PLUGIN_DEVEL=false'
        run: |
          git clone https://github.com/opnsense/plugins /usr/plugins
          rsync -av --exclude '.git' ./ /usr/plugins/net/opn-monitor/
          cd /usr/plugins/net/opn-monitor/
          make package
          cd -
          cp /usr/plugins/net/opn-monitor/work/pkg/* ./
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.pkg"
        generateReleaseNotes: true
        makeLatest: true
